
[appearance]
mode = "automatic"

[borders]
enabled = true
width = 3.0

[borders.color]
alpha = 1.0
blue = 0.979300037944676
green = 1.0
red = 0.08458520228437894

[focus]
followsMouse = false
followsWindowToMonitor = true
moveMouseToFocusedWindow = false

[gaps]
size = 16.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 0.0

[general]
backgroundTraceMaxBytes = 67108864
backgroundTraceRetentionSeconds = 0.0
debugBarEnabled = false
debugTraceExportCopiesFile = false
developerModeEnabled = true
dockShieldColorDarkHex = ""
dockShieldColorHex = "#1F1F1F"
dockShieldEnabled = false
dockShieldOpacity = 1.0
hotkeysEnabled = true
ignoreMonitorIdentity = false
ipcEnabled = true
preventSleepEnabled = false
viewportTraceVerbosity = "standard"

[gestures]
fingerCount = 3
invertDirection = true
overrideModifier = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0

[mouseWarp]
axis = "horizontal"
enabled = true
margin = 1
monitorOrder = []

[niri]
balancedColumnCount = 2
columnWidthPresets = [0.35, 0.5, 0.65, 0.95]
infiniteLoop = false
revealStyle = "auto"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = true
enabled = true
height = 26.0
hideEmptyWorkspaces = false
labelFontSize = 12.0
notchAware = true
position = "overlappingMenuBar"
reserveLayoutSpace = false
showFloatingWindows = true
showLabels = true
showScrollLockButton = false
showTraceButton = false
showWorkspacesFromOtherDisplays = false
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0
